services:
  worker:
    image: denoland/deno:latest
    command: deno run -A --unstable-cron app/src/main.ts
    container_name: worker
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    restart: always

volumes:
  data: